# Generated by Django 5.2.17 on 2026-09-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0003_order_last_checked_at_order_next_check_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="desktopauthorization",
            name="code_hash",
        ),
        migrations.AddField(
            model_name="desktopauthorization",
            name="last_polled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="release",
            name="minimum_os",
            field=models.CharField(default="12.0", max_length=20),
        ),
    ]
